name: traisformer
model_family: traisformer
dataset: ct_dma
seed: 123
input_steps: 18
output_steps: 72
num_modes: 16
batch_size: 32
evaluation_batch_size: 128
epochs: 50
early_stopping: false
patience: 5
grad_norm_clip: 1.0
num_workers: 4
normalize_input: false
max_seqlen: 120
training_sequence_len: 121
crop_policy: prefix
lat_size: 250
lon_size: 270
sog_size: 30
cog_size: 72
n_lat_embd: 256
n_lon_embd: 256
n_sog_embd: 128
n_cog_embd: 128
mode: pos
sample_mode: pos_vicinity
top_k: 10
r_vicinity: 40
sample_predictions: true
temperature: 1.0
blur: true
blur_learnable: false
blur_loss_w: 1.0
blur_n: 2
n_head: 8
n_layer: 8
embd_pdrop: 0.1
resid_pdrop: 0.1
attn_pdrop: 0.1
learning_rate: 0.0006
betas: [0.9, 0.95]
weight_decay: 0.1
warmup_steps: 500
